site_name: PIC2BIM DOCS
site_url: https://docs.pic2bim.co.uk

# draft_docs: |
#   drafts/

theme:
  logo: assets//images/logo_pic2bim_white.png
  name: 'material'
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    # navigation.instant      # WARN: breaks some javascripts
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - material/social
  - search
  - callouts
  - obsidian-interactive-graph
  - obsidian-bridge
  - glightbox
  - plantuml:
      puml_keyword: plantuml
      puml_url: https://www.plantuml.com/plantuml/

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - codehilite
  - md_in_html
  - def_list
  - sane_lists
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"

extra_css:
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/interactive_graph.css

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/obsidian_tags.js
  - assets/javascripts/interactive_graph.js